language: node_js
node_js:
  - "12.13.1"
dist: bionic
# group: edge # Not sure we need this anymore
sudo: required # To ensure we get a VM rather than a container for more memory and for all the apt-get stuff

env:
  global:
    # $TAGPERM environment variable
    # generate a token at https://github.com/settings/tokens and encrypt it
    # with `travis encrypt TAGPERM=<yoursecrettoken>`
    # also see: https://docs.travis-ci.com/user/encryption-keys/#Usage
    # and: https://docs.travis-ci.com/user/best-practices-security/
    - secure: "MMzx2PxzjMuJL7S74SxL3ZWdGiOqBh/geLJJIftY9ReswLVvJbxurB0PDYvdPw8E/bJ7ykWjR99mLBi2K7FV+SavBTVXEwvw8T8AO9TQe7x5RkIQu+jeM2wf8KfABPUDrdA7PlbA8cVO9LAUTBMTJ6E7x4+3khpqjmBZGxRzTAECDyHKeHIioDfRFkZsnn5JzcoiUk1TLk8snubIL7mE0euVylSdYUPHUO7OWe7DNzoOuWcXOQmIwuhTIDeKSv5aGLuLVbILvvngzFhpdr28dsapAgvJZMBC6dfGJbb59/RH3M7rE+WIOVjb1+npDxWsuhE8rAYJZIb5id0BqxjVyPJl05g+zIe8FICrNgRlTYqgF4uxrR02AvEAf0mDAHd+KralBA9sz8Q/IBmw7sfkq+8jYslLOa1GA/DDXjWJ/KGZPmIxj3HaMjjepyOjO2LIZIItQ2XsoUPDxra5BAUU5c7InKJpEiFw9dlhfjlJBJE1QBowUgVmlrrYBSI92mB8dQlYyyPBUP2pz5RoqnpBjyLg5vccAzWFiI76fRXmCXuZz51GmT+e2p6ZFD5rQ+KiTqpWIdz8vQ1jt+nRS9ufDzNgYeR0cykNmYnaJJETdi+LcZQefZcRN+X/bJqy4vLsYxxDSMo2IwsUgr/knSwdt4ZdKK2cDla0HyeKnwFAzOs="
    - RESOURCES_BRANCH: master
    - STROOM_TAG: v6-LATEST

before_install:
  - docker --version
  - docker-compose --version

before_script: ./travis.before_script.sh

install: echo "skip 'gradle assemble' step to speed up build"

script: ./travis.script.sh

## Push to GitHub releases for any tagged commit - the key was generated by the Travis CLI: `$ travis setup releases`
# deploy:
#  provider: releases
#  api_key:
#    secure: ttX6SnaA7XDS6lpUuSeGsLX5PSa3p8esJIu2DQIfsaWHg2svP8M5LcPMrN+hPINLjgKiUR/virhJLhvWtoOX7kH+K7sWYG94USg1RhhK5oFMtuuCxVS3/SDk2fgPy8rtVRCUlv8VuCDDnEZmN/JTIf8T0f7KOaqbH17/n4Egl42tvkIQ9FJexWOznYDQ9BuF+dRB5IP1NT0axyRvwVNTK1DIDKZ0M3MjP9sqvYkisqORuZdM5gwlOcsBTsuMUDJTHNv8B2PwyddCbPbFjkwcesR9AJdcxN3avL4FXshX1PbY7ZJa5NoGBlNsg8D3WNTKSTJxpE5xlpbSP2d1jDvql4am74iU/jmZ2Q9fdGu6zDVCnf5oLJLZ+epbsC4P4U/T8+7mHI7JwwdghnMy5w1JAPRiPsIoHA9Hy6jJzYCFriKArjEkMpb2s/ffsmP/tjDOpl+uNrJ5iWuzsLHjQtyCBUWcXb79saXsYeVi5lqljtOB0oZ5rJXgWrgcYT/A46sc0Uzej+RobawsGOluLWIUZM0mk+kgpCxYYNvqRMxzv6DVpBaXlYdvsyX0X7osBdM/SCcuT4MqoPN7Ez5NiEanO8XS2PzIQiv5FGBB2tJ6GbXHtHTtEKfBcX9gFl+n065D8YB6uSPPPWb8CpwMMDi1wXyK7DB5Ias3nGc70/LGKQw=
#  file: 
#    - stroom-persistence/src/scripts/transform_user_extract.py
#  skip_cleanup: true
#  on:
#    repo: gchq/stroom-ui
#    tags: true

# Clean out gradle caches as per travis docs
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

# Cache dependencies to speed up the build
cache:
  directories:
    - .autoconf
    - $HOME/.m2
    - libs
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

