export default {
  overlay: {
    // position: "fixed",
    // top: 0,
    // left: 0,
    // right: 0,
    // bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",

    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 100,

    opacity: 1,
    transition: "opacity 225ms cubic-bezier(0.4, 0, 0.2, 1) 0ms",
  },
  content: {
    // position: "absolute",
    // top: "50%",
    // left: "50%",
    // transform: "translate(-50%, -50%)",
    // right: '40px',
    // bottom: '40px',
    // border: "thin solid #ccc",
    // background: "#fff",
    // overflow: "auto",
    // WebkitOverflowScrolling: "touch",
    // borderRadius: "4px",
    outline: "none",
    // padding: "0",

    bottom: "unset",
    overflow: "visible",
    padding: 0,
    border: "none",
    borderRadius: 0,
    position: "static",
    background: "none",
    pointerEvents: "none",
  },
};
